### ISSUE TITLE
How to work with next-intl?

### ISSUE THREAD

**Issue by alex-guoba** [casdoor/nextjs-auth#9]
Hi guys, I have a question about the demo project.
In the middleware.ts.

```
const protectedRoutes = ["/profile"];

export default function middleware(req) {
  const casdoorUserCookie = req.cookies.get("casdoorUser");
  const isAuthenticated = casdoorUserCookie ? true : false;

  if (!isAuthenticated && protectedRoutes.includes(req.nextUrl.pathname)) {
    return NextResponse.redirect(new URL('/login', req.url))
  }
}
```

variable `req.nextUrl.pathname` may have some locale prefix if your import  `next-intl/` package in your project to support multi-language. So the proteced path can't be matched in this situation.  How to resolve it?

**Comment by hsluoyz** [comment]
@alex-guoba what URL patterns you use for i18n and which URLs need to be authenticated are just your own problem. It's your business logic, not something general that should be covered in this example
